dist: bionic
sudo: required
language: python
services:
  - docker
env:
  - DOCKER_IMAGE_NAME=vscoder/webdebugger
    DOCKER_IMAGE_TAG=${TRAVIS_COMMIT}
    DOCKER_USERNAME=${DOCKER_USERNAME}
    DOCKER_PASSWORD=${DOCKER_PASSWORD}
before_install:
  - python --version
  - pip --version
  - make --version
  - docker info
script:
  - echo DOCKER_USERNAME=$DOCKER_USERNAME
  - make hadolint
  - make build
  #- make docker-pycodestyle
  - make docker-pytest
  - make docker-version
deploy:
  provider: script
  script: bash docker-publish.sh
  on:
    tags: true
