dist: trusty
sudo: required
language: bash
before_install:
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-08/run.sh |
    bash
install:
  - ./.travis-scripts/install.sh
before_script:
  - ./.travis-scripts/before_script.sh
script:
  - ./.travis-scripts/script.sh
notifications:
  slack:
    rooms:
      secure: UaFHUCKI2v7guEx1Z+GW/1EUvA700rxg5xRWIsRPHPBMrQVyzYAyV9k/PFyeBVf+AUiSUXcpd+7V8GQcI3UcNn3ONaXUb+50eWGSdE7UB+4Iy+pio0S9gvP7cOLon37ny/d01ut7PcN7yRISZNOnpIv6yF2YnZYgIxy2+zTXjF255Y5Y5KiRysZ6lcogaUolfNRgsIq9P1v2yPaaCJA1VB24fmXVZN5TjqIMnbUT1zAH595CTV2ifUkUpBmYK6Qh36QxJI7WggI9xkYIs2R3No96RklMg3MGbD/1eYrYAjvbHptm4rCGPy0oL25KSNf1n+xTOxyKI0WnM9yxuoyrZVn/d+hHxbpsaoG+asziiHvzJsq4Zo3DRxIUbWW8f5gTx/Mzxlil8iC2YE0PaSmpuCJD7vAQVvYfNivmp0EdBZsnJDM/q3ZNsVggm4Z0QNGg8T6VCRgo2CaH3IAmN/BDFRKayb9oUCvJKpsdANe9QRFL41SydbkYi54IBD6/YXRiFqJ/P/s6V3yF6/3bRCkUgr6vrrIHX3Nznm9JRwU9CdYGMkPhKsumimv8L0EK2UJIPt54sPehpzx5IS4ujAimMZJFIb1De6Y05agUu/BY9fXj2U5FHGk7uM1K4tPr1r+qFb/Un0uua0zSBjRvEvptqo/sRJ0/cjjsk+Yg/vt3Mtk=
